pinger:
    geneart:
        server: https://www.thermofisher.com/order/gene-design-ordering/api
        validate: /validate/v1
        status: /status/v1
        addToCart: /addtocart/v1
        upload: /upload/v1
        username: YOUR_USERNAME
        token: YOUR_TOKEN
    twist:
        server: https://twist-api.twistbioscience-staging.com
        email: YOUR_EMAIL
        username: YOUR_USERNAME
        token: YOUR_TOKEN
controller:

review:
    db: 
        # https://docs.sqlalchemy.org/en/13/core/engines.html
        dialect: mysql 
        driver: 
        username: KeBqDrxA8ScfD9l7x1QhSprU9LjZVL
        password: z0uo6nK3l5thpph4uXykbMpwur6zgA
        host: db
        port: 3306
        database: review
