geneart:
    server: https://www.thermofisher.com/order/gene-design-ordering/api
    validate: /validate/v1
    status: /status/v1
    addToCart: /addtocart/v1
    upload: /upload/v1
    username: YOUR_USERNAME
    token: YOUR_TOKEN